use mentorMe_db;

INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Ernie", "Garcia", "egarcia@gmail.com", "qwerty", "http://dvcf.org/wordpress/wp-content/uploads/2014/01/Glen-Saunders-Thumb-250x200.jpg", "Irvine", "CA", "92570", "I have lots of experience and I would be happy to share it with you", "Web Development", "free", "Photoshop", "paid", "Javascript", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Louis", "Smith", "lsmith@gmail.com", "qwerty", "http://www.webbfound.org/wp-content/uploads/2010/08/Randy-250x200.jpg", "Newport Beach", "CA", "92571", "I have lots of experience and I would be happy to share it with you", "Web Development", "paid", "Photoshop", "paid", "Javascript", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Rhonda", "Lee", "rlee@gmail.com", "qwerty", "https://octaneseating.com/wp-content/uploads/2016/08/girl-computer.jpg", "Orange", "CA", "92572", "I have lots of experience and I would be happy to share it with you", "Web Development", "free", "Photoshop", "paid", "Javascript", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Beatrice", "Douglas", "bdouglas@gmail.com", "qwerty", "https://msgraphics.azureedge.net/content/employee_photos/Freedman_250x200.jpg", "Westminster", "CA", "92573", "I have lots of experience and I would be happy to share it with you", "Stocks", "free", "Trading", "paid", "Options", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Tom", "Nicholas", "tnicholas@gmail.com", "qwerty", "https://msgraphics.azureedge.net/cache/7/0/6/b/9/2/706b9235783ff75970240830539297aba496af82.jpg", "Huntington", "CA", "92574", "I have lots of experience and I would be happy to share it with you", "Stocks", "paid", "Trading", "paid", "Options", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Roger", "Brown", "rbrown@gmail.com", "qwerty", "https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/4/005/08c/205/255319d.jpg", "Brea", "CA", "92575", "I have lots of experience and I would be happy to share it with you", "Stocks", "free", "Trading", "paid", "Options", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Yanna", "Gonzales", "ygonzales@gmail.com", "qwerty", "http://kokefm.com/wp-content/uploads/2015/07/Bonnie-Bishop-060910-250x200.jpg", "Fullerton", "CA", "92576", "I have lots of experience and I would be happy to share it with you", "Guitar", "free", "Drums", "paid", "Keyboard", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Larry", "Johnson", "ljohnson@gmail.com", "qwerty", "http://musicwhynot.com/wp-content/uploads/2017/09/2017-09-02_1217-250x200.png", "Stanton", "CA", "92577", "I have lots of experience and I would be happy to share it with you", "Guitar", "free", "Drums", "paid", "Keyboard", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Tony", "Cross", "tcross@gmail.com", "qwerty", "http://kzum.org/wp-content/uploads/midland_band-250x200.jpg", "Newport Beach", "CA", "92570", "I have lots of experience and I would be happy to share it with you", "Guitar", "free", "Drums", "paid", "Keyboard", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Johnny", "Cash", "anguyen@gmail.com", "qwerty", "https://minkinsmusic.files.wordpress.com/2016/10/johnny-cash-02.jpg?w=250&h=200&crop=1", "Los Angeles", "CA", "92571", "I have lots of experience and I would be happy to share it with you", "Guitar", "free", "Drums", "paid", "Keyboard", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Luke", "Ross", "lross@gmail.com", "qwerty", "https://ymcanwnc.org/wp-content/uploads/2016/06/High-Res-JPG-250x200.jpg", "Crenshaw", "CA", "92572", "I have lots of experience and I would be happy to share it with you", "Weightlifting", "free", "Nutrition", "paid", "Crossfit", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Dana", "Mathews", "dmathews@gmail.com", "qwerty", "https://ymcanwnc.org/wp-content/uploads/2016/08/2014-06-25_AOF_11979_RGB-250x200.jpg", "Watts", "CA", "92573", "I have lots of experience and I would be happy to share it with you", "Weightlifting", "free", "Nutrition", "paid", "Crossfit", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Brittney", "Reed", "breed@gmail.com", "qwerty", "https://www.exede.com/wp-content/uploads/2016/08/iStock_85597567_SMALL-250x200.jpg", "Long Beach", "CA", "92574", "I have lots of experience and I would be happy to share it with you", "Math", "paid", "Statistics",  "free", "Accounting", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Sam", "Brady", "sbrady@gmail.com", "qwerty", "https://s3-eu-west-1.amazonaws.com/tutors.firsttutors.com/80/79546/med.jpg", "Inglewood", "CA", "92575", "I have lots of experience and I would be happy to share it with you", "Math", "free", "Statistics",  "paid", "Accounting", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Amanda", "White", "awhite@gmail.com", "qwerty", "http://rebeccawatson.org/wp-content/uploads/ewpt_cache/250x200_100_1_c_FFFFFF_9911063eb3e84b2231281c1da7cb850a_scan-3.jpg", "Costa Mesa", "CA", "92576", "I have lots of experience and I would be happy to share it with you", "Sketching", "paid", "Painting", "free", "Drawing", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Mary", "Duke", "mduke@gmail.com", "qwerty", "http://echslawndale.org/wp-content/uploads/2017/06/DanniWashington2017_headshot-250x200.jpg", "Fountain Valley", "CA", "92577", "I have lots of experience and I would be happy to share it with you", "Fashion", "paid", "Film", "free", "Photography", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Faith", "Garcia", "fgarcia@gmail.com", "qwerty", "http://hospitalitymgt.com/site/wp-content/uploads/2016/03/Ruthie-Web-380-x-304-2.jpg", "Santa Margarita", "CA", "92570", "I have lots of experience and I would be happy to share it with you", "Sales", "paid", "Marketing", "paid", "Networking", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Brad", "Smith", "bsmith@gmail.com", "qwerty", "http://wnixradio.com/wp-content/uploads/2016/09/larry_kudlow-01-250x200.jpg", "Tustin", "CA", "92571", "I have lots of experience and I would be happy to share it with you", "Sales", "free", "Marketing", "free", "Networking", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Monica", "Lee", "mlee@gmail.com", "qwerty", "https://i1.wp.com/socalpreplegends.com/wp-content/uploads//2016/05/ciara-edgewood.jpg", "Lake Forest", "CA", "92572", "I have lots of experience and I would be happy to share it with you", "Volleyball", "free", "Basketball", "paid", "Exercise", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Eden", "Douglas", "edouglas@gmail.com", "qwerty", "https://i0.wp.com/socalpreplegends.com/wp-content/uploads//2015/12/OMARISMITH.png", "Mission Viejo", "CA", "92573", "I have lots of experience and I would be happy to share it with you", "Volleyball", "paid", "Basketball", "free", "Exercise", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Cathy", "Nicholas", "cnicholas@gmail.com", "qwerty", "http://socalpreplegends.com/wp-content/uploads//2015/09/loryn-carter.jpg", "San Diego", "CA", "92574", "I have lots of experience and I would be happy to share it with you", "Volleyball", "free", "Basketball", "paid", "Exercise", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Tanya", "Brown", "tbrown@gmail.com", "qwerty", "http://r.ddmcdn.com/s_f/o_1/TLC/uploads/2014/07/jasmine-frank-250x200.jpg", "The Valley", "CA", "92575", "I have lots of experience and I would be happy to share it with you", "Cooking", "free", "Baking", "paid", "Event Planning", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Brin", "Gonzales", "bgonzales@gmail.com", "qwerty", "http://r.ddmcdn.com/s_f/o_1/TLC/uploads/2014/07/marissa-lopez-250x200.jpg", "Seal Beach", "CA", "92576", "I have lots of experience and I would be happy to share it with you", "Cooking", "paid", "Baking", "paid", "Event Planning", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Nicole", "Johnson", "njohnson@gmail.com", "qwerty", "http://blog.ecu.edu/sites/cfac/files/2015/09/HopkinsWeb.jpg", "Sunset Beach", "CA", "92577", "I have lots of experience and I would be happy to share it with you", "Presentations", "paid", "Powerpoint", "paid", "Public Speaking", "paid");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Gretchen", "Garcia", "ggarcia@gmail.com", "qwerty", "https://www.rcm.org.uk/sites/default/files/legacy/midwives_article/250x200-lesley-closing-speech.jpg", "Hollywood", "CA", "92570", "I have lots of experience and I would be happy to share it with you", "Presentations", "free", "Powerpoint", "free", "Public Speaking", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Charlie", "Smith", "csmith@gmail.com", "qwerty", "http://socalpreplegends.com/wp-content/uploads//2015/09/courtney.jpg", "Santa Ana", "CA", "92571", "I have lots of experience and I would be happy to share it with you", "Soccer", "free", "Nutrition", "paid", "Running", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Natalie", "Lee", "nlee@gmail.com", "qwerty", "https://i.pinimg.com/564x/13/56/3a/13563a1d7c9333651ff980045849d637--soccer-pics-soccer-quotes.jpg", "Garden Grove", "CA", "92572", "I have lots of experience and I would be happy to share it with you", "Soccer", "free", "Juggling", "paid", "Exercise", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Fiona", "Douglas", "fdouglas@gmail.com", "qwerty", "https://i0.wp.com/lariatnews.com/wp-content/uploads/2016/12/Breanna-Taboada.jpg?resize=250%2C200", "Santa Ana", "CA", "92573", "I have lots of experience and I would be happy to share it with you", "Soccer", "free", "Juggling", "paid", "Exercise", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Diane", "Nicholas", "dnicholas@gmail.com", "qwerty", "https://sward.d123.org/wp-content/uploads/sites/7/2016/07/SchiestelMrs-250x200.jpg", "Irvine", "CA", "92574", "I have lots of experience and I would be happy to share it with you", "Spanish", "free", "English",  "paid", "French", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Victor", "Brown", "vbrown@gmail.com", "qwerty", "http://www.2girls1asian.com/uploads/1/5/5/4/15546350/1495488.jpeg", "Dana Point", "CA", "92575", "I have lots of experience and I would be happy to share it with you", "Chinese", "free", "Korean", "paid", "Japanese", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Cynthia", "Gonzales", "cgonzales@gmail.com", "qwerty", "https://i.pinimg.com/736x/20/15/21/201521159d88f30210324f2bc49c38b3--female-surfers-nike-ad.jpg", "Aliso Viejo", "CA", "92576", "I have lots of experience and I would be happy to share it with you", "Surfing", "paid", "Sailing", "paid", "Wind Surfing", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Paul", "Johnson", "pjohnson@gmail.com", "qwerty", "http://www.oxexpeditions.com/images/SurfGuatemalaSalvador/Guatemala%20Surf%20Main%20Menu%20Tab.jpg", "Dana Point", "CA", "92577", "I have lots of experience and I would be happy to share it with you", "Surfing", "free", "Wind Surfing", "paid", "Sailing", "free");


SELECT * FROM mentorMe_db.Users;